Evaluacion3/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Evaluacion3.Models;

namespace Evaluacion3.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly AppDbContext _context;

        public CategoriaController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index() // Views - Marcas - Index
        {
            var Categoria = _context.tblCategorias.ToList();
            return View(Categoria);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Categoria C)
        {
            if (C == null) return View();

            if (ModelState.IsValid)
            {
                _context.Add(C);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(C);
        }

        [HttpGet]
        public IActionResult Edit(int IdCategoria)
        {
            var C = _context.tblCategorias.FirstOrDefault(m => m.Id == IdCategoria);
            if (C == null) return NotFound();
            else
            {
                return View(C);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Categoria C)
        {
            if (ModelState.IsValid)
            {
                _context.Update(C);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(C);
        }


        [HttpGet]
        public IActionResult Delete(int IdCategoria)
        {
            var C = _context.tblCategorias.FirstOrDefault(m => m.Id == IdCategoria);
            if (C == null) return NotFound();
            else
            {
                return View(C);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Categoria C)
        {
            _context.Remove(C);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



    }
}

Evaluacion3/Controllers/ClaseController.cs
using Microsoft.AspNetCore.Mvc;
using Evaluacion3.Models;

namespace Evaluacion3.Controllers
{
    public class ClaseController : Controller
    {
        private readonly AppDbContext _context;

        public ClaseController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index() // Views - Marcas - Index
        {
            var Clase = _context.tblclases.ToList();
            return View(Clase);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Clase C)
        {
            if (C == null) return View();

            if (ModelState.IsValid)
            {
                _context.Add(C);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(C);
        }

        [HttpGet]
        public IActionResult Edit(int IdClase)
        {
            var Clase = _context.tblclases.FirstOrDefault(c => c.Id == IdClase);
            if (Clase == null) return NotFound();
            else
            {
                return View(Clase);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Clase Clase)
        {
            if (ModelState.IsValid)
            {
                _context.Update(Clase);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Clase);
        }


        [HttpGet]
        public IActionResult Delete(int IdClase)
        {
            var Clase = _context.tblclases.FirstOrDefault(m => m.Id == IdClase);
            if (Clase == null) return NotFound();
            else
            {
                return View(Clase);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Clase Clase)
        {
            _context.Remove(Clase);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



    }
}

Evaluacion3/Controllers/HomeController.cs
using Evaluacion3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Evaluacion3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Evaluacion3/Controllers/caracteristicasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Evaluacion3.Models;
using Evaluacion3.ModelsView;

namespace Evaluacion3.Controllers
{
    public class caracteristicasController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;
        public caracteristicasController(AppDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
   

        public IActionResult CrearEquipo()
        {
            ViewData["Marcas"] = new SelectList(_context.tblmarcas.ToList(), "Id", "Name");
            ViewData["Tipos"] = new SelectList(_context.tblTipos.ToList(), "Id", "Name");
            ViewData["Categorias"] = new SelectList(_context.tblCategorias.ToList(), "Id", "Name");
            ViewData["Clase"] = new SelectList(_context.tblclases.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CrearCaracteristica(caracteristicas C)
        {
            if (ModelState.IsValid)
            {
                if (C.ImagenFile == null) C.ImagenUrl = "no-disponible.png";
                else
                {
                    string wwwRootPath = _environment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(C.ImagenFile.FileName);
                    string extension = Path.GetExtension(C.ImagenFile.FileName);
                    C.ImagenUrl = fileName + DateTime.Now.ToString("ddMMyyyyHHmmss") + extension; //foto08062022131545.png 

                    string path = Path.Combine(wwwRootPath + "/img/" + C.ImagenUrl);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await C.ImagenFile.CopyToAsync(fileStream);
                    }
                }
                _context.Add(C);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(C);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var C = _context.tblcaracteristicas.Find(Id);
            if (C == null) return NotFound();
            _context.Remove(C);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> Edit(int Id)
        {
            var C = await _context.tblcaracteristicas.FindAsync(Id);
            if (C == null) return NotFound();
            return View(C);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(caracteristicas C)
        {
            if (ModelState.IsValid)
            {
                if (C.ImagenFile == null) C.ImagenUrl = "no-disponible.png";
                else
                {
                    string wwwRootPath = _environment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(C.ImagenFile.FileName);
                    string extension = Path.GetExtension(C.ImagenFile.FileName);
                    C.ImagenUrl = fileName + DateTime.Now.ToString("ddMMyyyyHHmmss") + extension; //foto08062022131545.png 

                    string path = Path.Combine(wwwRootPath + "/img/" + C.ImagenUrl);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await C.ImagenFile.CopyToAsync(fileStream);
                    }
                }
                _context.Update(C);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(C);
        }




    }
}

Evaluacion3/Controllers/marcaController.cs
using Microsoft.AspNetCore.Mvc;
using Evaluacion3.Models;

namespace Evaluacion3.Controllers
{
    public class marcaController : Controller
    {
        private readonly AppDbContext _context;

        public marcaController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index() // Views - Marcas - Index
        {
            var marca = _context.tblmarcas.ToList();
            return View(marca);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(marca M)
        {
            if (M == null) return View();

            if (ModelState.IsValid)
            {
                _context.Add(M);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(M);
        }

        [HttpGet]
        public IActionResult Edit(int Idmarca)
        {
            var marca = _context.tblmarcas.FirstOrDefault(m => m.Id == Idmarca);
            if (marca == null) return NotFound();
            else
            {
                return View(marca);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Edit(marca marca)
        {
            if (ModelState.IsValid)
            {
                _context.Update(marca);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }


        [HttpGet]
        public IActionResult Delete(int Idmarca)
        {
            var marca = _context.tblmarcas.FirstOrDefault(m => m.Id == Idmarca);
            if (marca == null) return NotFound();
            else
            {
                return View(marca);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(marca marca)
        {
            _context.Remove(marca);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



    }
}

Evaluacion3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div class="text-center">
    <div class="row mt-2">

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-registered" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Marcas</h5>
                    <p class="card-text">Crea, Edita o Elimina Marcas en el Sistema para la administracion y gestion de Equipos vehiculos!</p>
                    <a asp-controller="marca" asp-action="Index"
                       class="btn btn-outline-danger col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card p-3">
                <i class="fa-solid fa-clipboard-list"  style="font-size:5rem;" ></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Categorias</h5>
                    <p class="card-text">Crea, Edita o Elimina Categorias en el Sistema para la administracion y gestion de Equipos vehiculos!</p>
                    <a asp-controller="Categoria" asp-action="Index"
                       class="btn btn-outline-success col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card p-3">
           <i class="fa-solid fa-list-ul" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Tipos</h5>
                    <p class="card-text">Crea, Edita o Elimina Tipos en el Sistema para la administracion y gestion de vehiculos!</p>
                    <a asp-controller="Tipo" asp-action="Index"
                       class="btn btn-outline-primary col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>


    </div>
    <div class="row mt-2">

        <div class="col-lg-4">
            <div class="card p-3">
               <i class="fa-solid fa-car-rear" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Caracteristicas</h5>
                    <p class="card-text">Gestion de caracteristicas del vehiculo</p>
                    <a asp-controller="caracteristicas" asp-action="Index"
                       class="btn btn-outline-info col-12">Ir a la Administracion</a>
                </div>
            </div>
        </div>
       
        

        <div class="col-lg-4">
            <div class="card p-3">
              <i class="fa-solid fa-car" style="font-size:5rem;"></i>
                <div class="card-body">
                    <h5 class="card-title">Administracion de Clases</h5>
                    <p class="card-text">Gestion del tipo de vehiculo</p>
                    <a asp-controller="Clase" asp-action="Index"
                       class="btn btn-outline-info col-12">Ir a la Clase</a>
                </div>
            </div>
        </div>

       
    